name: 정적 코드 분석
on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Java 설치
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: 정적 코드 분석
        run: ./gradlew detekt --continue
